# Generated by Django 5.2.5 on 2025-08-20 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulte',
            options={'ordering': ['-date_consultation'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_articles.article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_articles.utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_commentaire'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_articles.article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_articles.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'article')},
            },
        ),
    ]
