# Generated by Django 5.2.5 on 2025-08-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articles', '0002_alter_consulte_options_alter_utilisateur_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-date_like']},
        ),
        migrations.AlterField(
            model_name='article',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='gestion_articles.souscategorie'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gestion_articles.article'),
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
