# Generated by Django 5.2.5 on 2025-08-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_centreinteret_article_categorie_abonnement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='centres_interet',
            new_name='centre_interet',
        ),
    ]
