# Generated by Django 5.2.5 on 2025-08-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0003_rename_centres_interet_utilisateur_centre_interet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contenu',
        ),
    ]
