# Generated by Django 5.2.5 on 2025-09-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0004_rename_content_article_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='model3D',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article', to='myApi.souscategorie'),
        ),
    ]
