# Generated by Django 5.2.5 on 2025-09-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0005_article_model3d_alter_article_sous_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='model3D',
        ),
        migrations.AddField(
            model_name='article',
            name='modele_3d',
            field=models.FileField(blank=True, help_text='Fichier 3D au format .glb ou .gltf', null=True, upload_to='models/'),
        ),
    ]
