# Generated by Django 5.2.5 on 2025-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0006_remove_article_model3d_article_modele_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='modele_3d',
        ),
        migrations.AddField(
            model_name='article',
            name='model3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/'),
        ),
    ]
