# Generated by Django 5.2.5 on 2025-09-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0007_remove_article_modele_3d_article_model3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='model3d',
        ),
        migrations.AddField(
            model_name='article',
            name='modele_3d',
            field=models.FileField(blank=True, help_text='Fichier 3D au format .glb ou .gltf', null=True, upload_to='models/'),
        ),
    ]
